labelm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magazin.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazin/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    #BASE
    path('', home, name='home'),
    #Products
    path('product', product_list, name='product'),
    #Register
    path('register', register, name='register'),
    #Cart
    path('cart', cart, name='cart'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    #Checkout
    path('checkout', checkout, name='checkout'),
    path('confirmation', confirmation, name='confirmation'),
    #Login
    path('login', user_login, name='login'),
    #Logout
    path('logout', user_logout, name='logout'),
    #Profile
    path('profile', profile, name='profile'),
    #Order-History
    path('order_history', order_history, name='order_history'),
    #Reset Password Logic!
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #Invoice
    path('generate_invoice/<int:order_id>/', generate_invoice, name='generate_invoice'),
    path('invoices/', invoice_list, name='invoice_list'),
    path('invoices/<int:invoice_id>/', invoice_detail, name='invoice_detail'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

magazin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    available = models.BooleanField(default= True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name}"

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Cart item: #{self.user.username} - {self.product.name} (Quantity: {self.quantity}) - #{self.created}"
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_address = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=50)
    full_name = models.CharField(max_length=255)
    
    def __str__(self):
        return f"Order #{self.id} by {self.user.username} to {self.shipping_address} with a total of {self.total_price} Lei in {self.payment_method}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"OrderItem #{self.pk}"
    
class ShippingAddress(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

class Invoice(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    invoice_number = models.CharField(max_length=255, unique=True)
    pdf = models.FileField(upload_to='invoices/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Invoice #{self.invoice_number} - {self.created_at}"

magazin/forms.py
from django import forms

################# FORMS VALIDATION for Checkout! #################

class CheckoutForm(forms.Form):
    full_name = forms.CharField(label='Full Name', required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your full name'}))
    city = forms.CharField(label='City', required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your city'}))
    shipping_address = forms.CharField(label='Shipping Address', required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your shipping address'}))
    email = forms.EmailField(label='Email Address', required=True, widget=forms.EmailInput(attrs={'placeholder': 'Enter your email address'}))
    phone = forms.CharField(label='Phone Number', required=True, widget=forms.TextInput(attrs={'type': 'tel', 'placeholder': 'Enter your phone number'}))
    payment_method = forms.ChoiceField(
        label='Payment Method',
        required=True,
        widget=forms.RadioSelect,
        choices=[
            ('credit-card', 'Credit Card'),
            ('cash', 'Cash'),
        ]
    )

magazin/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
from .forms import CheckoutForm
from .models import Category, Product, Cart, Order , OrderItem, Invoice
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
from django.db import transaction
from .utils.pdf_utils import generate_invoice_pdf, generate_unique_invoice_number
from django.core.files.base import ContentFile
from django.utils import timezone

# Create your views here.

####################################################################### PRODUCT LIST!!! ############################################################################
def product_list(request):
    selected_category_id = request.GET.get('category')
    if selected_category_id:
        selected_category = get_object_or_404(Category, id=selected_category_id)
        products = Product.objects.filter(category=selected_category)
    else:
        products = Product.objects.all()
        selected_category = None
    
    categories = Category.objects.all()
    context = {
        'products': products,
        'selected_category': selected_category,
        'categories': categories,
    }
    return render(request, 'product_list.html', context)

def home(request):
    return render(request, 'home.html')

####################################################################### HOME!!! ############################################################################
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password_confirm = request.POST.get('password_confirm')

        #Check password if is True!
        if not any(char.isalpha() for char in password) or not any(char.isdigit() for char in password):
            messages.error(request, "Your password must contain both letters and digits.")
            return render(request, 'register.html', {'username': username, 'email': email})

        if len(password) < 8:
            messages.error(request, "Your password must contain at least 8 characters.")
            return render(request, 'register.html', {'username': username, 'email': email})

        if password != password_confirm:
            messages.error(request, "Passwords do not match.")
            return render(request, 'register.html', {'username': username, 'email': email})
        
        # Check if the username or email is already taken
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username is already taken.")
            return render(request, 'register.html', {'email': email})

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email is already taken.")
            return render(request, 'register.html', {'username': username})
        
         # Create a new user and save to the database
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        # After successful registration, redirect to the confirmation page
        return redirect('confirmation') 

    return render(request, 'register.html')

####################################################################### CART!!! ############################################################################
def cart(request):
    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
        total_quantity = sum(item.quantity for item in cart_items)

        for item in cart_items:
            item.subtotal = item.product.price * item.quantity

        context = {
            'cart_items': cart_items,
            'cart_count': total_quantity,
        }
    else:
        context = {
            'cart_items': [],
            'cart_count': 0,
        }

    return render(request, 'cart.html', context)

####################################################################### ADD_TO_CART!!! ############################################################################
def add_to_cart(request, product_id):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, id=product_id)
        
        try:
            cart = Cart.objects.get(user=request.user, product=product)
        except Cart.DoesNotExist:
            # If the cart item doesn't exist, create a new one
            cart = Cart(user=request.user, product=product, quantity=0, subtotal=0)

        # Calculate the subtotal
        subtotal = product.price

        cart.quantity += 1
        cart.subtotal += subtotal  # Update the subtotal
        cart.save()

        return redirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect('login')

####################################################################### REMOVE_FROM_CART!!! ############################################################################

def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_item = get_object_or_404(Cart, user=request.user, product=product)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.subtotal -= product.price
        cart_item.save()
    else:
        cart_item.delete()
    
    return redirect('cart')

####################################################################### CONFIRMATION!!! ############################################################################
def confirmation(request):
    if request.method == 'POST':
        
        return redirect('confirmation')  # 'confirmation' is the URL name for the confirmation page

    return render(request, 'confirmation.html')

####################################################################### USER-LOGIN!!! ############################################################################
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')  # Redirect to the user's profile page or another page
        else:
            messages.error(request, "Invalid login credentials.")
            return render(request, 'login.html', {'username': username})
        
    return render(request, 'login.html')

####################################################################### LOGOUT!!! ############################################################################
def user_logout(request):
    logout(request)
    return redirect('home') # Redirect to the home

####################################################################### PROFILE!!! ############################################################################

@login_required
def profile(request):
    return render(request, 'profile.html') # Redirect to the profile page

####################################################################### CHECKOUT ##################################################################
###################################################################################################################################################

@login_required
def checkout(request):
    user = request.user
    cart_items = Cart.objects.filter(user=user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)  # Calculate total price

    error_message = ""

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            total_order_price = total_price
            payment_method = form.cleaned_data['payment_method']

            if payment_method == 'credit-card':
                # Display a message indicating that Credit Card payment is not available
                error_message = "Credit Card payment is not available. Please choose another payment method."
            else:
                try:
                    with transaction.atomic():
                        # Create the order within a database transaction
                        order = Order.objects.create(
                            user=user,
                            shipping_address=form.cleaned_data['shipping_address'],
                            payment_method=payment_method,
                            total_price=total_order_price,  # Use the updated total price
                            full_name=full_name,
                        )

                    for cart_item in cart_items:
                        order_item = OrderItem.objects.create(
                            order=order,
                            product=cart_item.product,
                            quantity=cart_item.quantity,
                            subtotal=cart_item.subtotal
                        )
                        order.products.add(cart_item.product)  # Associate the product with the order

                    cart_items.delete()
                    
                    # Generate the invoice PDF and get the next invoice number
                    pdf_buffer, invoice_number = generate_invoice_pdf(order, full_name)

                    # Save the PDF to the invoice

magazin/templates/cart.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}
{% load total_price %}

     <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}/">

<h1>CART</h1>
{% for cart_item in cart_items %}
    <div class="cart-item">
        <h4>{{ cart_item.product.name }}</h4>
        {% if cart_item.product.image %}
            <img src="{{ cart_item.product.image.url }}" alt="{{ cart_item.product.name }}">
        {% else %}
            <div class="unknown-product">Unknown product</div>
        {% endif %}
        <div class="cart-item-details">
            <a><b>Price: </b><span class="price">{{ cart_item.product.price }}</span></a>
            <a><b>Subtotal: </b><span class="subtotal">{{ cart_item.subtotal }}</span></a>
            <a href="{% url 'add_to_cart' cart_item.product.id %}" class="cart-button">+</a>
            <a><b>{{ cart_item.quantity }}</b></a>
            <a href="{% url 'remove_from_cart' cart_item.product.id %}" class="cart-button">-</a>
        </div>
    </div>
{% empty %}
    <p>Your cart is empty.</p>
{% endfor %}

{% if cart_items %}
    <div class="order-total">
        <div>
            <span class="total-label">Total Price:</span>
            <span class="total-amount">{{ cart_items|total_price }} Lei</span>
        </div>
        <a href="{% url 'checkout' %}" class="checkout-button">Proceed to Checkout</a>
    </div>
{% endif %}


{% endblock mainblock %}

magazin/templates/confirmation.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

<h2>Thank You!</h2>
<p>Welcome to our e-commerce platform.</p>


{% endblock mainblock %}

magazin/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Label.M Romania</title>
</head>
<body>
    {% include 'navbar.html' %}
    

    {% load static%}
     <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    {% block mainblock %}
        
        <video autoplay="True" loop="loop" id="video" onclick="this.paused?this.play():this.pause();"><source src="https://cdn.shopify.com/videos/c/o/v/a5a26a250350433a9de779eeb50acfef.mp4" type="video/mp4"><source src="" type="video/ogg"></video></section>


    {% endblock mainblock %}

</body>
<footer>
{% include 'social.html' %}
</footer>
</html>

magazin/templates/invoice_detail.html
{% extends 'home.html' %}
{% load static %}
{% block mainblock %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/invoice_detail.css' %}">

  <h1 class="invoice-detail-title">Invoice Detail</h1>
  <p class="invoice-id">Invoice ID: {{ invoice.id }}</p>
  <a href="{{ invoice.pdf.url }}" download class="download-pdf-button">Download PDF</a>
  <a href="{% url 'invoice_list' %}" class="back-to-list-button">Back to Invoice List</a>

{% endblock mainblock %}

magazin/templates/invoice_list.html
{% extends 'home.html' %}
{% load static %}

{% block mainblock %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/invoice_list.css' %}/">

  <h1 class="invoice-list-title">Invoice List</h1>
  <ul class="invoice-list">
    {% for invoice in invoices %}
      <li class="invoice-item">
        <a href="{% url 'invoice_detail' invoice.id %}" class="invoice-link">Invoice {{ invoice.id }}</a>
        <br>
        <strong class="invoice-date-label">Invoice Date:</strong> {{ invoice.created_at }}
      </li>
    {% empty %}
      <li class="no-invoices">No invoices available.</li>
    {% endfor %}
  </ul>
{% endblock mainblock %}

magazin/templates/login.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}/"> 

<h2>Login</h2>
<div class="login-container">
    <div class="login-form">
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
            {% endif %}
        <form method="post">
            {% csrf_token %}
        <div>
            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" required>
        </div>
        <div>
            <label for="id_password">Password:</label>
            <input type="password" id="id_password" name="password" required>
        </div>
        <button type="submit">Login</button>
        </form>
    </div>
</div>
{% endblock mainblock %}

magazin/templates/navbar.html
{% url 'product' as Products %}
{% url 'home' as Home %}
{% url 'cart' as Cart %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}/">    

<img src="https://cdn.shopify.com/s/files/1/1277/2557/t/19/assets/logo.png?v=179722150632437446431668422935" alt="Label.m Romania" class="center">

<div class="navbar">
    <ul>
        <div class='left-items'>
        <li><a href="{% url 'home' %}">Label.M</a></li>
        <li><a href="{% url 'product' %}">SHOP</a></li>
        </div>
        <div class="right-items">
        {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="22" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
            </svg> Profile</a></li>
            <li><a href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-door-closed-fill" viewBox="0 0 16 16">
                <path d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg> Logout</a></li>
        {% else %}
            <li><a href="{% url 'register' %}">Register</a></li>
            <li><a href="{% url 'login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
                <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z"/>
            </svg>Login</a></li>
        {% endif %}
        <li class="cart-items123">
            <a href="{% url 'cart' %}" class="cart-link">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                </svg><span class="cart-count">{{ cart_count }}</span>
            </a>
        </li>
        <div>
    </ul>
</div>

magazin/templates/order_history.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/order_history.css' %}">

<div class="container">
    <h1>Welcome, {{ user.username }}!</h1>

    <h2>Your Orders:</h2>
    {% if orders_with_products %}
    <ul>
        {% for order_with_products in orders_with_products %}
            <li class="order-box">
                <strong>Order ID:</strong> <span class="red-text">{{ order_with_products.order.id }}</span><br>
                <strong>Total Price:</strong> <span class="red-text"> {{ order_with_products.order.total_price }}Lei</span><br>
                <strong>Shipping Address:</strong> {{ order_with_products.order.shipping_address }}<br>
                <strong>Payment Method:</strong> {{ order_with_products.order.payment_method }}<br>
                <strong>Ordered Products:</strong>
                <ul>
                    {% for order_item in order_with_products.order.orderitem_set.all %}
                        <li>
                        <img src="{{ order_item.product.image.url }}" alt="{{ order_item.product.name }}" class="product-image">
                        {{ order_item.product.name }} - Price: {{ order_item.product.price }} Lei<span>
                        - Quantity Ordered: {{ order_item.quantity }}
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You have no orders yet.</p>
    {% endif %}
</div>
{% endblock mainblock %}

magazin/templates/password_reset.html
{% extends "home.html" %}
{% load static %}
{% block mainblock %}


<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset.css' %}">


  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class="mt-4 mb-4">Reset Your Password</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email address</label>
            {{ form.email }}
          </div>
          <button type="submit" class="btn btn-primary">Reset Password</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

magazin/templates/password_reset_complete.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <h2>Password Reset Complete</h2>
                <p>Your password has been successfully reset.</p>
                <p>You can now <a href="{% url 'login' %}">log in</a> with your new password.</p>
            </div>
        </div>
    </div>

{% endblock %}

magazin/templates/password_reset_confirm.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset_confirm.css' %}">

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Reset Your Password</h2>
            <p>Please enter a new password for your account.</p>
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <label for="{{ form.new_password1.id_for_label }}">New Password</label>
                    {{ form.new_password1 }}
                </div>
                <div class="form-group">
                    <label for="{{ form.new_password2.id_for_label }}">Confirm New Password</label>
                    {{ form.new_password2 }}
                </div>
                <button type="submit" class="btn btn-primary">Reset Password</button>
            </form>
            <div id="password-alert" class="alert alert-danger mt-3" style="display: none;">
                Password must meet the following requirements:
                <ul>
                    <li>At least 8 characters long</li>
                    <li>Contain both uppercase and lowercase letters</li>
                    <li>Contain at least one digit (0-9)</li>
                </ul>
            </div>
            <script>
                document.querySelector('form').addEventListener('submit', function (event) {
                    const password1 = document.querySelector('#{{ form.new_password1.id_for_label }}').value;
                    const password2 = document.querySelector('#{{ form.new_password2.id_for_label }}').value;
                    const alert = document.querySelector('#password-alert');

                    if (password1.length < 8 || !/[a-z]/.test(password1) || !/[A-Z]/.test(password1) || !/\d/.test(password1)) {
                        event.preventDefault(); // Prevent form submission
                        alert.style.display = 'block';
                    }
                });
            </script>
        </div>
    </div>
</div>
{% endblock %}

magazin/templates/password_reset_done.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}

{% block mainblock %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <h2>Password Reset Request Sent</h2>
                <p>An email has been sent to your registered email address with instructions on how to reset your password.</p>
                <p>Please check your email and follow the provided link to reset your password.</p>
                <p>If you do not receive an email within a few minutes, please check your spam folder.</p>
            </div>
        </div>
    </div>

{% endblock %}

magazin/templates/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
    <div class="container">
        <h1>Password Reset</h1>
        <p>Hello,</p>
        <p>You have requested to reset your password for your account at <strong>Label.M</strong>. To complete the process, please click the link below:</p>
        <p><a href="http://localhost:8000{% url 'password_reset_confirm' uidb64=uid token=token %}">Reset Password</a></p>
        <p>If you did not request this password reset, please ignore this email. Your password will not be changed.</p>
        <p>Thank you,</p>
        <p><strong>Label.M Team</strong></p>
    </div>
</body>
</html>

magazin/templates/profile.html
{% extends "home.html" %}
{% include navbar.html %}
{% load static %}
{% block mainblock %}

<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">


    <h1>Welcome, {{ user.username }}!</h1>


    <h2>Quick Links</h2>
    <ul>
        <li><a href="{% url 'order_history' %}">Order History</a></li>
        <li><a href="{% url 'invoice_list' %}">Invoices</a></li>
    </ul>


{% endblock mainblock %}